"""Kevin - a creativity-routing architecture (vendored into Doktores).

Creativity is not generated by relaxing constraints, but by *routing* between
unexplored solution spaces, wild variation, method transfer, and epistemic
selection - and then letting a human choose meaning and direction.

This is an improved in-house copy of the upstream Kevin, adapted to Doktores'
conventions (``DOKTORES_USE_REAL_LLM`` toggle, key priority DeepSeek > OpenRouter >
OpenAI) and extended with grounding, executed-method transfer, combinatorial
blind-spot pairs, a falsification/hardening loop, a Pareto + novelty-floor selector,
domain-tagged Layer-9 learning, diversity pressure and a multi-persona ensemble.

Public surface:

    from doktores.kevin import Kevin, Problem
    from doktores.kevin import build_briefing

    kevin = Kevin()
    run = kevin.run(Problem("how do we make onboarding feel less like paperwork?"))
    print(build_briefing(run).render())
"""

from __future__ import annotations

from .human_gate import Briefing, build_briefing
from .method_library import MethodLibrary, extract_method
from .models import (
    Affinity,
    Candidate,
    CreativeRun,
    Evaluation,
    Method,
    Problem,
    SolutionSpace,
    Variant,
    Verdict,
    WildMove,
)
from .orchestrator import Kevin
from .selector import diverse_slate

__all__ = [
    "Kevin",
    "Problem",
    "SolutionSpace",
    "Variant",
    "Method",
    "Candidate",
    "Evaluation",
    "CreativeRun",
    "MethodLibrary",
    "extract_method",
    "diverse_slate",
    "Briefing",
    "build_briefing",
    "Affinity",
    "Verdict",
    "WildMove",
]

__version__ = "0.1.0"
