"""Kevin - the orchestrator (the Dirigent).

This is the whole architecture in one routing pass. It owns no creativity of its
own; it *routes* between the engines in the order the design prescribes, and records
everything into a replay-stable ``CreativeRun``.

    1. explore       - find plausible, under-worked solution spaces (+ pairs)
    2. route         - select only the under-explored ones                 (logic)
    3. vary          - send the wild brother in (optionally as an ensemble)  (LLM)
    4. transfer      - discipline the wildest variants with Layer-9 methods (execute)
    5. select        - keep what is coherent / testable / connected         (selection)
    6. harden        - falsify the top candidates and revise once           (loop)
    7. brief         - hand a ranked possibility space to the human         (no decision)

The thesis, in code:

    Creativity is not generated by relaxing constraints, but by routing between
    unexplored solution spaces, wild variation, method transfer, and epistemic
    selection. The human chooses meaning and direction.
"""

from __future__ import annotations

from .llm_client import LLMClient, get_default_client
from .method_library import MethodLibrary
from .models import Candidate, CreativeRun, Problem, Variant
from .selector import Selector, diverse_slate
from .solution_space import SolutionSpaceExplorer
from .space_predictor import SpacePredictor
from .wild_brother import WildBrother


class Kevin:
    def __init__(
        self,
        llm: LLMClient | None = None,
        *,
        library: MethodLibrary | None = None,
    ) -> None:
        self._llm = llm or get_default_client()
        self._explorer = SolutionSpaceExplorer(self._llm)
        self._predictor = SpacePredictor()
        self._wild = WildBrother(self._llm)
        self._library = library or MethodLibrary()
        self._selector = Selector(self._llm)

    @property
    def library(self) -> MethodLibrary:
        return self._library

    def run(
        self,
        problem: Problem,
        *,
        top_spaces: int = 2,
        methods_per_target: int = 2,
        discipline_threshold: float = 0.7,
        personas: int = 1,
        harden: bool = True,
        max_harden: int = 2,
    ) -> CreativeRun:
        """One full creative pass. Deterministic given the same LLM.

        ``discipline_threshold`` decides which variants are wild enough to *need* a
        transferred method: the tamer ones go forward as raw candidates, the wildest
        ones are disciplined by Layer 9 - the strongest case in the design.

        ``personas`` (improvement 8) runs the wild brother as a divergence-harvesting
        ensemble when > 1. ``harden`` (improvement 4a) runs one bounded falsification
        round over the top ``max_harden`` candidates.
        """
        run = CreativeRun(problem=problem)

        # 0. predict where the open solution spaces are (blind-spot coverage),
        #    then seed the explorer with those regions (single axes + distant pairs).
        prediction = self._predictor.predict(problem)
        run.space_prediction = prediction.to_dict()

        # 1-2. explore and route to under-worked, plausible regions. Explore exactly
        # once, then route over *those* spaces: under a real (non-deterministic) LLM a
        # second explore() would yield different spaces with different ids.
        seeds = [*prediction.seed_spaces, *prediction.pair_spaces]
        run.spaces = self._explorer.explore(problem, extra_spaces=seeds)
        chosen = self._explorer.pick(run.spaces, top_k=top_spaces)
        run.chosen_spaces = [s.id for s in chosen]

        # 3. wild variation, only inside the routed spaces (optionally an ensemble).
        run.variants = self._wild.storm(problem, chosen, personas=personas)

        # 4-5. build candidates: raw for tame variants, method-disciplined for wild ones.
        space_by_id = {s.id: s for s in run.spaces}
        for variant in run.variants:
            if variant.wildness >= discipline_threshold:
                run.candidates.extend(
                    self._discipline(run, variant, space_by_id, methods_per_target)
                )
            else:
                run.candidates.append(self._raw_candidate(variant))

        run.evaluations = self._selector.select(problem, run.candidates)
        run.pareto_ids = [e.candidate_id for e in run.evaluations if e.pareto]

        # 6. harden: falsify the top candidates and revise once (bounded).
        if harden:
            self._harden(run, problem, max_harden)

        return run

    # -- helpers ------------------------------------------------------------ #
    def _raw_candidate(self, variant: Variant) -> Candidate:
        return Candidate(
            content=variant.content,
            space_id=variant.space_id,
            variant_id=variant.id,
            wildness=variant.wildness,
        )

    def _discipline(
        self, run: CreativeRun, variant: Variant, space_by_id: dict, methods_per_target: int
    ) -> list[Candidate]:
        """Transfer matching Layer-9 methods onto a wild variant -> disciplined candidates."""
        space = space_by_id.get(variant.space_id)
        affinities = space.affinities if space else ()
        methods = self._library.match(
            affinities, top_k=methods_per_target, prefer_domain=run.problem.domain
        )
        if not methods:
            return [self._raw_candidate(variant)]

        candidates: list[Candidate] = []
        for method in methods:
            transfer = self._library.transfer(
                self._llm,
                method,
                variant.id,
                variant.content,
                problem_statement=run.problem.statement,
                variables=run.problem.variables,
            )
            run.transfers.append(transfer)
            disciplined_text = (
                f"{variant.content}  |  via '{method.name}': "
                + "; ".join(transfer.mapped_steps)
            )
            candidates.append(
                Candidate(
                    content=disciplined_text,
                    space_id=variant.space_id,
                    variant_id=variant.id,
                    transfer_id=transfer.id,
                    wildness=variant.wildness,
                    method_name=method.name,
                )
            )
        return candidates

    def _harden(self, run: CreativeRun, problem: Problem, max_harden: int) -> None:
        """Falsification loop: attack the top candidates and add one revised version each.

        Bounded and deterministic: only the top ``max_harden`` candidates (by score) are
        hardened, exactly one revised candidate is produced per attack, and the revisions
        are not themselves re-hardened. Both the original and the hardened candidate are
        kept and (re-)evaluated, so the human sees the before and the after.
        """
        by_id = {c.id: c for c in run.candidates}
        top = [
            e for e in run.evaluations if e.candidate_id in by_id
        ][:max_harden]
        new_candidates: list[Candidate] = []
        for ev in top:
            base = by_id[ev.candidate_id]
            critique = self._llm.critique(problem, base.content)
            weakness = critique.get("weakness", "")
            fix = critique.get("suggested_fix", "")
            hardened = Candidate(
                content=(
                    f"{base.content}  ||  hardened against weakness "
                    f"('{weakness}'): {fix}"
                ),
                space_id=base.space_id,
                variant_id=base.variant_id,
                transfer_id=base.transfer_id,
                wildness=base.wildness,
                method_name=base.method_name,
                hardened_from=base.id,
            )
            new_candidates.append(hardened)
            run.hardened.append(hardened.id)

        if not new_candidates:
            return
        run.candidates.extend(new_candidates)
        # Re-select over the full set so the hardened candidates get scored and the
        # Pareto front reflects them too.
        run.evaluations = self._selector.select(problem, run.candidates)
        run.pareto_ids = [e.candidate_id for e in run.evaluations if e.pareto]

    # -- diversity (improvement 7) ----------------------------------------- #
    def diverse_slate(self, run: CreativeRun, k: int = 3):
        """A spread-maximising top-k over the run's evaluations (delegates to selector)."""
        return diverse_slate(run.evaluations, run.candidates, k)
